export const productos = [
  {
    id: "1",
    nombre: "La Breve Original",
    descripcion: "Nuestra bebida clásica con el sabor que nos hizo famosos.",
    descripcionLarga:
      "La Breve Original es nuestra bebida insignia, la que inició todo. Con una mezcla perfectamente equilibrada de ingredientes naturales, ofrece un sabor único que ha conquistado a miles de personas. Cada sorbo es una experiencia que combina tradición e innovación, creando una sensación refrescante y satisfactoria que te acompañará en cualquier momento del día. Elaborada con los más altos estándares de calidad, La Breve Original es más que una bebida, es una experiencia que debes probar.",
    precio: "$35",
    categoria: "clasicos",
    imagen: "/placeholder.svg?height=600&width=600",
    imagenes: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    ingredientes: "Agua purificada, extractos naturales, azúcar de caña, ácido cítrico, saborizantes naturales.",
    beneficios: "Refrescante, energizante natural, sin conservantes artificiales.",
    presentaciones: ["Botella 355ml", "Botella 500ml", "Lata 355ml", "Six-pack"],
  },
  {
    id: "2",
    nombre: "La Breve Cítrico",
    descripcion: "Una explosión de sabores cítricos para refrescarte.",
    descripcionLarga:
      "La Breve Cítrico es una explosión de frescura en cada sorbo. Combinando los mejores cítricos como limón, naranja y toronja, hemos creado una bebida que despierta tus sentidos y te transporta a un oasis de frescura. Perfecta para los días calurosos o cuando necesitas ese toque revitalizante. Su sabor equilibrado entre dulce y ácido crea una experiencia única que te hará volver por más. Como todos nuestros productos, La Breve Cítrico está elaborada con ingredientes naturales de la más alta calidad.",
    precio: "$38",
    categoria: "frutales",
    imagen: "/placeholder.svg?height=600&width=600",
    imagenes: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    ingredientes: "Agua purificada, jugo de limón, jugo de naranja, jugo de toronja, azúcar de caña, ácido cítrico.",
    beneficios: "Rico en vitamina C, antioxidantes naturales, refrescante.",
    presentaciones: ["Botella 355ml", "Botella 500ml", "Lata 355ml", "Six-pack"],
  },
  {
    id: "3",
    nombre: "La Breve Tropical",
    descripcion: "Combinación perfecta de frutas tropicales.",
    descripcionLarga:
      "La Breve Tropical te transporta a un paraíso de sabores exóticos. Hemos seleccionado las mejores frutas tropicales como piña, mango y maracuyá para crear una bebida que evoca vacaciones en la playa y días soleados. Cada sorbo es un viaje sensorial a través de sabores dulces y refrescantes que se complementan a la perfección. La Breve Tropical es ideal para quienes buscan una experiencia diferente, una aventura de sabor que rompe con lo cotidiano mientras mantiene la calidad y naturalidad que caracteriza a todos nuestros productos.",
    precio: "$38",
    categoria: "frutales",
    imagen: "/placeholder.svg?height=600&width=600",
    imagenes: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    ingredientes: "Agua purificada, jugo de piña, puré de mango, jugo de maracuyá, azúcar de caña, ácido cítrico.",
    beneficios: "Fuente de vitaminas, refrescante, energizante natural.",
    presentaciones: ["Botella 355ml", "Botella 500ml", "Lata 355ml", "Six-pack"],
  },
  {
    id: "4",
    nombre: "La Breve Intenso",
    descripcion: "Para los que buscan un sabor más fuerte y pronunciado.",
    descripcionLarga:
      "La Breve Intenso está diseñada para aquellos que buscan una experiencia más robusta y pronunciada. Con un perfil de sabor más concentrado y una fórmula especial que potencia cada ingrediente, esta bebida ofrece una intensidad que despierta los sentidos desde el primer sorbo. Perfecta para los paladares exigentes que aprecian los sabores profundos y complejos. A pesar de su intensidad, mantiene el equilibrio perfecto que caracteriza a La Breve, ofreciendo una experiencia satisfactoria que perdura. Como parte de nuestra línea premium, La Breve Intenso representa la excelencia en cada detalle.",
    precio: "$40",
    categoria: "premium",
    imagen: "/placeholder.svg?height=600&width=600",
    imagenes: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    ingredientes: "Agua purificada, extractos concentrados, especias seleccionadas, azúcar moreno, ácido cítrico.",
    beneficios: "Experiencia sensorial completa, energizante natural, sin conservantes artificiales.",
    presentaciones: ["Botella 355ml", "Botella 500ml", "Edición especial 750ml"],
  },
  {
    id: "5",
    nombre: "La Breve Light",
    descripcion: "El mismo gran sabor con menos calorías.",
    descripcionLarga:
      "La Breve Light ofrece toda la experiencia de sabor que caracteriza a nuestros productos, pero con un perfil bajo en calorías. Hemos trabajado arduamente para desarrollar una fórmula que mantenga el delicioso sabor que nos distingue mientras reducimos significativamente el contenido calórico. Utilizando edulcorantes naturales y una combinación especial de ingredientes, La Breve Light es la opción perfecta para quienes cuidan su ingesta calórica sin querer sacrificar el placer de disfrutar una bebida excepcional. Refrescante, satisfactoria y con todo el carácter de La Breve.",
    precio: "$38",
    categoria: "clasicos",
    imagen: "/placeholder.svg?height=600&width=600",
    imagenes: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    ingredientes: "Agua purificada, extractos naturales, stevia, eritritol, ácido cítrico, saborizantes naturales.",
    beneficios: "Bajo en calorías, sin azúcares añadidos, refrescante.",
    presentaciones: ["Botella 355ml", "Botella 500ml", "Lata 355ml", "Six-pack"],
  },
  {
    id: "6",
    nombre: "La Breve Frutos Rojos",
    descripcion: "Deliciosa mezcla de fresas, frambuesas y moras.",
    descripcionLarga:
      "La Breve Frutos Rojos es una sinfonía de sabores que combina la dulzura de las fresas, la intensidad de las frambuesas y el carácter de las moras. Esta mezcla cuidadosamente equilibrada crea una experiencia frutal rica y satisfactoria que deleita el paladar. Cada sorbo revela capas de sabor que se complementan perfectamente, ofreciendo una complejidad que los amantes de las frutas apreciarán. Además de su delicioso sabor, La Breve Frutos Rojos aporta los beneficios naturales de estas frutas, conocidas por sus propiedades antioxidantes. Una opción refrescante y nutritiva para cualquier momento del día.",
    precio: "$42",
    categoria: "frutales",
    imagen: "/placeholder.svg?height=600&width=600",
    imagenes: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    ingredientes: "Agua purificada, puré de fresa, puré de frambuesa, puré de mora, azúcar de caña, ácido cítrico.",
    beneficios: "Rico en antioxidantes, vitaminas naturales, refrescante.",
    presentaciones: ["Botella 355ml", "Botella 500ml", "Edición especial 750ml"],
  },
  {
    id: "7",
    nombre: "La Breve Edición Especial",
    descripcion: "Nuestra edición limitada con ingredientes exclusivos.",
    descripcionLarga:
      "La Breve Edición Especial representa la cumbre de nuestra artesanía en la creación de bebidas excepcionales. Elaborada en lotes limitados con ingredientes exclusivos seleccionados de las mejores fuentes alrededor del mundo, esta bebida ofrece una experiencia verdaderamente única. Su fórmula cambia estacionalmente, aprovechando los mejores ingredientes de temporada y permitiéndonos explorar nuevas combinaciones de sabores. Cada edición es irrepetible, lo que la convierte en una experiencia coleccionable para los entusiastas de La Breve. Presentada en un envase distintivo, La Breve Edición Especial es perfecta como regalo o para celebrar ocasiones especiales.",
    precio: "$45",
    categoria: "premium",
    imagen: "/placeholder.svg?height=600&width=600",
    imagenes: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    ingredientes:
      "Agua de manantial, ingredientes de temporada seleccionados, especias exóticas, edulcorantes naturales.",
    beneficios: "Experiencia sensorial única, ingredientes exclusivos, edición limitada.",
    presentaciones: ["Botella premium 500ml", "Caja regalo 2 botellas", "Edición coleccionista 750ml"],
  },
  {
    id: "8",
    nombre: "La Breve Menta",
    descripcion: "Refrescante sabor a menta para los días calurosos.",
    descripcionLarga:
      "La Breve Menta ofrece una experiencia refrescante incomparable. Utilizando extracto de menta de la más alta calidad, hemos creado una bebida que proporciona una sensación de frescura inmediata y duradera. Su sabor limpio y vigorizante es perfecto para combatir el calor o para disfrutar después de una comida. La sutileza de la menta se equilibra perfectamente con la dulzura natural, creando una armonía que no abruma sino que invita a seguir disfrutando. La Breve Menta es especialmente popular entre quienes buscan una alternativa refrescante a las bebidas frutales tradicionales, ofreciendo una experiencia diferente pero igualmente satisfactoria.",
    precio: "$38",
    categoria: "clasicos",
    imagen: "/placeholder.svg?height=600&width=600",
    imagenes: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    ingredientes: "Agua purificada, extracto de menta, azúcar de caña, ácido cítrico, saborizantes naturales.",
    beneficios: "Extremadamente refrescante, digestivo natural, sensación de frescura duradera.",
    presentaciones: ["Botella 355ml", "Botella 500ml", "Lata 355ml", "Six-pack"],
  },
]
