export const productos = [
  {
    id: "1",
    nombre: "La Breve Original",
    descripcion: "Nuestra bebida clásica con el sabor que nos hizo famosos.",
    descripcionLarga:
      "La Breve Original es nuestra bebida insignia, la que inició todo. Con una mezcla perfectamente equilibrada de ingredientes naturales, ofrece un sabor único que ha conquistado a miles de personas. Cada sorbo es una experiencia que combina tradición e innovación, creando una sensación refrescante y satisfactoria que te acompañará en cualquier momento del día. Elaborada con los más altos estándares de calidad, La Breve Original es más que una bebida, es una experiencia que debes probar.",
    precio: "$6.000 COP",
    categoria: "clasicos",
    imagen: "/products/original.png",
    imagenes: [
      "/products/original.png",
    ],
    ingredientes: "Agua purificada, extractos naturales, azúcar de caña, ácido cítrico, saborizantes naturales.",
    beneficios: "Refrescante, energizante natural, sin conservantes artificiales.",
    presentaciones: ["Botella 355ml", "Botella 500ml", "Lata 355ml", "Six-pack"],
  },
  {
    id: "2",
    nombre: "La Breve Cítrica",
    descripcion: "Una combinación de malta con toques vibrantes de limón, naranja y maracuyá.",
    descripcionLarga:
      "La Breve Cítrica combina malta con vibrantes notas cítricas de limón, naranja y maracuyá. Su equilibrio entre acidez y frescura crea una bebida refrescante, con un aroma que resalta en cada sorbo. Ideal para quienes buscan un sabor fresco y ácido.",
    precio: "$6.000 COP",
    categoria: "frutales",
    imagen: "/products/citrica.png",
    imagenes: ["/products/citrica.png"],
    ingredientes: "Malta, jugo de limón, jugo de naranja, maracuyá, agua carbonatada.",
    beneficios: "Refrescante, cítrica, perfecta para climas cálidos.",
    presentaciones: ["Lata 232ml", "Botella 340ml (Ed. Vidrio)", "Botella 473ml", "Edición especial Sombría"],
  },
  {
    id: "3",
    nombre: "La Breve Tropical",
    descripcion: "Una fusión exótica de malta con mango, piña y coco.",
    descripcionLarga:
      "La Breve Tropical ofrece una mezcla dulce y refrescante de mango, piña y coco. Una bebida que evoca la esencia de una escapada al Caribe, perfecta para quienes buscan un balance entre dulzura y frescura con un toque exótico.",
    precio: "$6.000 COP",
    categoria: "frutales",
    imagen: "/products/tropical.png",
    imagenes: ["/products/tropical.png"],
    ingredientes: "Malta, mango, piña, coco, agua carbonatada.",
    beneficios: "Dulce, exótica, refrescante.",
    presentaciones: ["Lata 232ml", "Botella 473ml", "Edición especial"],
  },
  {
    id: "4",
    nombre: "La Breve Frutos Rojos",
    descripcion: "Intensa mezcla de fresa, cereza y arándanos. Claro, con su toque unico de malta",
    descripcionLarga:
      "La Breve Frutos Rojos es una combinación intensa de malta con fresa, cereza y arándanos. Ideal para quienes buscan una bebida dulce y vibrante, con notas afrutadas y un ligero toque ácido que le da un carácter único.",
    precio: "$6.000 COP",
    categoria: "frutales",
    imagen: "/products/frutos_rojos.png",
    imagenes: ["/products/frutos_rojos.png"],
    ingredientes: "Malta, fresa, cereza, arándanos, agua carbonatada.",
    beneficios: "Dulce, frutal, antioxidante natural.",
    presentaciones: ["Lata 232ml", "Botella 473ml", "Sombría 440ml"],
  },
  {
    id: "5",
    nombre: "La Breve Disco",
    descripcion: "La edición especial en vidrio con sabor original.",
    descripcionLarga:
      "La Breve Disco es una versión en botella de vidrio de 340ml con un diseño vibrante y exclusivo. Conserva el sabor original que caracteriza a La Breve, ideal para celebraciones o momentos especiales.",
    precio: "$10.000 COP",
    categoria: "especial",
    imagen: "/products/disco.jpg",
    imagenes: ["/products/disco.jpg"],
    ingredientes: "Malta, extractos naturales, agua carbonatada.",
    beneficios: "Presentación especial, sabor clásico.",
    presentaciones: ["Botella de vidrio 340ml"],
  },
  {
    id: "6",
    nombre: "La Brevisima",
    descripcion: "La versión agrandada para más sabor.Más Breve, más sabor.",
    descripcionLarga:
      "La Brevisima es la versión más grande de nuestra bebida clásica, con 473ml. Conserva el mismo sabor y calidad de siempre, perfecta para quienes quieren disfrutar más de La Breve.",
    precio: "$8.000 COP",
    categoria: "clasicos",
    imagen: "/products/brevisima.jpg",
    imagenes: ["/products/brevisima.jpg"],
    ingredientes: "Malta, saborizantes naturales, agua carbonatada.",
    beneficios: "Formato más grande, ideal para compartir.",
    presentaciones: ["Botella 473ml"],
  },
  {
    id: "7",
    nombre: "La Breve Sombría",
    descripcion: "Versión para los más curiosos. Unica en su especie",
    descripcionLarga:
      "La Breve Sombría es una versión única con sabor a moras silvestres y granada. Con una presentación oscura y elegante, está diseñada para quienes buscan sabores intensos y diferentes. Disponible en botella de 440ml.",
    precio: "$9.000 COP",
    categoria: "especial",
    imagen: "/products/crepusculo.jpg",
    imagenes: ["/products/crepusculo.jpg"],
    ingredientes: "Mora silvestre, granada, malta, agua carbonatada.",
    beneficios: "Sabor intenso, presentación elegante.",
    presentaciones: ["Botella 440ml"],
  },
]
